apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-nlb-controller.fullname" . }}-metrics
  labels:
    {{- include "aws-nlb-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "aws-nlb-controller.selectorLabels" . | nindent 4 }}
